--- 
DEBUG: True
DB_ENGINE: "Postgres"
APP_DIR: ""
APP_PORT: 5000
SECRET_KEY: "Geoscience Australia Rocks" # Fake key for development and testing
IGSN_URI_BASE: "http://pid.geoscience.gov.au/samples/sample/"
IGSN_LOG: "dataset_metadata_cache.log"
LOGFILE: "dataset_metadata_cache.log"
LOGLEVEL: "WARNING"
POSTGRES_SERVER: "localhost"
POSTGRES_PORT: 5432
POSTGRES_DBNAME: "dataset_metadata_cache"
POSTGRES_USER: "db_user"
POSTGRES_PASSWORD: "s3<r3t!!"
LOCAL_TIMEZONE: "AEDT"