field_definitions: # Overrides for short_name, long_name & units keyed by original field name.
  DOI: {short_name: depth_of_investigation, units: m}
  DataResidual: {long_name: Data residual, short_name: data_residual}
  Residual2: {long_name: Data residual 2, short_name: data_residual2}
  Residual3: {long_name: Data residual 3, short_name: data_residual3}
  StdDev_TxHeightInverted: {long_name: Uncertainty of the inverted height
      of the TXRX frame, short_name: stddev_tx_height_inverted, units: m}
  TotalResidual: {long_name: Total Residual, short_name: total_residual}
  TxHeightInverted: {long_name: Inverted height of the TXRX frame, short_name: tx_height_inverted,
    units: m}
  TxHeightMeasured: {long_name: Measured height of the TXRX frame, short_name: tx_height_measured,
    units: m}
  depth_top: {long_name: Depth to the top of the layer, short_name: layer_top_depth, units: m}
  easting: {long_name: UTM Easting (x) ordinate, short_name: easting, units: m}
  elevation: {long_name: Ground elevation relative to sea-level, short_name: elevation,
    units: m}
  line: {long_name: Line number, short_name: line}
  nlayers: {long_name: layers, short_name: layers}
  ndatlm: {long_name: low moment gates, short_name: low_moment_gates}
  ndathm: {long_name: high moment gates, short_name: high_moment_gates}
  northing: {long_name: UTM Northing (y) ordinate, short_name: northing, units: m}
  resistivity: {long_name: Layer resistivity, short_name: resistivity,
    units: ohm.m}
  conductivity: {long_name: Layer conductivity, short_name: conductivity,
    units: S/m}
  resistivity_uncertainty: {long_name: Uncertainty of the layer resistivity,
    short_name: resistivity_uncertainty}
  sequence: {long_name: Inversion sequence number, short_name: sequence}
  data_values: {long_name: Data values measured at each gate, short_name: data_values, units: V/(A.turns.m4)}
  data_response: {long_name: Data response, short_name: data_response}
  data_relative_uncertainty: {long_name: Relative uncertainty of data value, short_name: data_relative_uncertainty}
keywords: geophysics, airborne, AEM, conductivity # String containing comma-separated list of keywords
dimension_fields: [layers, low_moment_gates, high_moment_gates] # List of posisble dimension field names