# Global settings
global_settings:
  debug: false
  http_compression: false # Set this to false for local use, true for remote
  database_engine: SQLite
  # Define number of line segments to show across bounding box height for line sub-sampling
  line_segments_across_bbox: 100

# Default dataset settings
default_dataset_settings:
  dataset_link: null
  filtered_point_icon_color: ff000000
  height_variable: null
  line_color: ff32cd9a
  line_width: 5
  point_color_settings: ff32cd9a
  point_field_list: null
  point_icon_href: 'http://maps.google.com/mapfiles/kml/paddle/grn-blank.png'
  point_icon_scale: 0.7
  point_labelstyle_scale: 0
  polygon_color: 1
  timestamp_detail_view: false
  
# Dataset settings
dataset_settings:
  ground_gravity:
    dataset_format: point
    min_polygon_bbox_width: 1.5 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [AUS, ground digital data, gravity, geophysical survey, points]
    dataset_type_name: Ground Gravity Surveys
    netcdf_path_prefix: C:\Temp\Geophysics\gravity point datasets # Local directory containing files. Use null to use OPeNDAP
    point_color_settings: # Parameters for point color display defined as: (<field_name>: (<color_range_min>, <color_range_max>)) or static color
    - bouguer
    - [-500, 500]
    point_field_list: [obsno, latitude, longitude, grav, freeair, bouguer, stattype, reliab, gridflag]
    point_filter: {gridflag: Station not used in the production of GA grids.} # Dict containing field names & values to filter out
    point_icon_href: http://maps.google.com/mapfiles/kml/paddle/grn-blank.png
    point_icon_scale: 0.7
    point_labelstyle_scale: 0
    polygon_color: B30000ff # Red
    polygon_outline: 1
    protocol: opendap
    dataset_link: http://dapds00.nci.org.au/thredds/catalog/uc0/rr2_dev/axi547/ground_gravity/point_datasets/catalog.html?dataset=uc0/rr2_dev/axi547/ground_gravity/point_datasets/{netcdf_basename}
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  aem:
    dataset_format: line
    min_polygon_bbox_width: 15.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [geophysics, airborne, AEM, conductivity]
    dataset_type_name: AEM Surveys
    netcdf_path_prefix: C:\Temp\Geophysics\AEM conductivity datasets # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ff32cd9a # Bright Green
    polygon_outline: 1
    line_color: ff32cd9a
    line_width: 5
    protocol: opendap
    dataset_link: http://dapds00.nci.org.au/thredds/catalog/uc0/rr2_dev/axi547/aem/catalog.html?dataset=uc0/rr2_dev/axi547/aem/{netcdf_basename}
    height_variable: lidar # Do not set this value for 2D coordinates
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  magnetic_grids:
    dataset_format: grid
    min_polygon_bbox_width: 0.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, magnetics, grid]
    dataset_type_name: Magnetic Survey grids
    netcdf_path_prefix: C:\Temp\Geophysics\magnetic grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ffff0000 # Blue
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  potassium_grids:
    dataset_format: grid
    min_polygon_bbox_width: 0.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, radiometrics, potassium, grid]
    dataset_type_name: Potassium Survey grids
    netcdf_path_prefix: C:\Temp\Geophysics\radiometric grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ff808080 # Grey
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  thorium_grids:
    dataset_format: grid
    min_polygon_bbox_width: 0.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, radiometrics, thorium, grid]
    dataset_type_name: Thorium Equivalent Survey grids
    netcdf_path_prefix: C:\Temp\Geophysics\radiometric grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ffffff00 # Cyan
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
  uranium_grids:
    dataset_format: grid
    min_polygon_bbox_width: 0.0 # maximum bounding box width for detailed display. Uses survey convex-hull polygons for anything larger.
    keyword_list: [NCI, geophysical survey, airborne digital data, radiometrics, uranium, grid]
    dataset_type_name: Uranium Equivalent Survey grids
    netcdf_path_prefix: C:\Temp\Geophysics\radiometric grids # Local directory containing files. Use null to use OPeNDAP
    polygon_color: ff800080 # Purple
    polygon_outline: 1
    protocol: opendap
    dataset_link: 'https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/{metadata_uuid}'
    colormap_name: rainbow
    color_count: 256
    timestamp_detail_view: true
 