ground_gravity:
  format: point
  keyword_list: [AUS, ground digital data, gravity, geophysical survey, points]
  netcdf_file_folder_name: Ground Gravity Surveys
  netcdf_path_prefix: C:\Temp\gravity point_datasets # Local directory containing files. Leave empty to use OPeNDAP
  point_colour: # Parameters for point colour display defined as: (<field_name>: (<colour_range_min>, <colour_range_max>)) or static colour
  - bouguer
  - [-500, 500]
  point_field_list: [obsno, latitude, longitude, grav, freeair, bouguer, stattype, reliab, gridflag]
  point_filter: {gridflag: Station not used in the production of GA grids.} # Dict containing field names & values to filter out
  point_icon_href: http://maps.google.com/mapfiles/kml/paddle/grn-blank.png
  point_icon_scale: 0.7
  point_labelstyle_scale: 0
  polygon_color: B30000ff
  polygon_outline: 1
  protocol: opendap
  thredds_link: http://dapds00.nci.org.au/thredds/catalog/uc0/rr2_dev/axi547/ground_gravity/point_datasets/catalog.html?dataset=uc0/rr2_dev/axi547/ground_gravity/point_datasets/
aem:
  format: line
  keyword_list: [geophysics, airborne, AEM, conductivity]
  netcdf_file_folder_name: AEM Surveys
  netcdf_path_prefix: C:\Temp\AEM conductivity datasets # Local directory containing files. Leave empty to use OPeNDAP
  point_field_list: [line_index, latitude, longitude, lidar, mag, gps_elevation]
  point_icon_href: http://maps.google.com/mapfiles/kml/paddle/grn-blank.png
  point_icon_scale: 0.7
  point_labelstyle_scale: 0
  polygon_color: B30000ff
  polygon_outline: 1
  line_colour: ff32cd9a
  line_width: 5
  protocol: opendap
  thredds_link: http://dapds00.nci.org.au/thredds/dodsC/uc0/rr2_dev/axi547/aem/
  